---
# Logs aren't persisted by journald, persistent logs are sent over the wire to the log server
- name: Configure RAM-based logging
  copy:
    dest: /etc/systemd/journald.conf
    content: |
      [Journal]
      Storage=volatile
      RuntimeMaxUse=30M
      MaxFileSec=1week
      SystemMaxUse=50M
  notify: Restart journald

- name: Ensure rsyslog is installed
  apt:
    name: rsyslog
    state: present

- name: Copy rsyslog configuration
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify: Restart rsyslog

- name: Copy logrotate configuration (remote file)
  template:
    src: logrotate-remote-logs.j2
    dest: /etc/logrotate.d/remote-logs
  notify: Restart logrotate
