---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Install iptables
  apt:
    name: iptables
    state: present

- name: Ensure WireGuard directory exists
  file:
    path: "/etc/wireguard"
    state: directory

- name: Setup WireGuard config
  template:
    src: wg.conf.j2
    dest: "{{ wg_config_file }}"
  notify: Restart wireguard

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Ensure WireGuard is up and running
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
