---
- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Ensure WireGuard directory exists
  file:
    path: "/etc/wireguard"
    state: directory

- name: Setup WireGuard config
  template:
    src: wg.conf.j2
    dest: "{{ wg_config_file }}"
  notify: Restart wireguard

- name: Ensure WireGuard is up and running
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
