- name: Install the CA public key on the device
  copy:
    content: "{{ ssh_keys.ca.public_key }}"
    dest: /etc/ssh/ca.pub
    owner: root
    group: root
    mode: '0644'

- name: Configure SSH to trust the CA
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?TrustedUserCAKeys'
    line: 'TrustedUserCAKeys /etc/ssh/ca.pub'
    state: present
  notify: Restart SSH
