---
- name: Check if Pi-hole binary exists
  stat:
    path: /usr/local/bin/pihole
  register: pihole_installed

# Install dependencies
- name: Install required packages for Pi-hole
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  when: not pihole_installed.stat.exists

# Download Pi-hole installer script
- name: Download Pi-hole installation script
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/pihole_install.sh
    mode: '0755'
  when: not pihole_installed.stat.exists

# Instruct user to manually run Pi-hole installer
- name: Fail if Pi-hole is not installed, with manual instructions
  fail:
    msg: "Pi-hole is not installed. Please run the following command on the Pi-hole device to install it: 'sudo bash /tmp/pihole_install.sh'"
  when: not pihole_installed.stat.exists
