---
- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart journald
  service:
    name: systemd-journald
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
