---
- name: Install unattended-upgrades
  apt:
    name:
      - unattended-upgrades
    state: present

- name: Ensure unattended-upgrades config directory exists
  file:
    path: /etc/apt/apt.conf.d
    state: directory
    mode: '0755'

- name: Configure unattended-upgrades
  template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    mode: "0644"
  notify: Restart unattended-upgrades

- name: Configure auto-upgrades
  template:
    src: "20auto-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    mode: "0644"
  notify: Restart unattended-upgrades

- name: Ensure unattended-upgrades is enabled
  systemd:
    name: unattended-upgrades
    enabled: yes
